version: "3.9"
services:
  user-db:
    image: postgres:10.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/user/data
volumes:
  postgres: ~
