version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "summms"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m3eoi3wk1djh"
s3_prefix = "summms"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
